Fix String related PMD Warnings
dsldevkit/dsl-devkit pull request #827
Opened 2023-11-08 13:35 UTC by rubenporras

2023-11-08 13:38 UTC, joaodinissf requested changes

2023-11-08 14:57 UTC, rubenporras commented on com.avaloq.tools.ddk.check.ui/src/com/avaloq/tools/ddk/check/ui/wizard/NewCheckProjectWizard.java
> +    if (projectInfo.getPackageName().chars().allMatch(Character::isWhitespace)) {
I think so.

2023-11-08 14:58 UTC, joaodinissf submitted a review, later dismissed

2023-11-08 15:39 UTC, joaodinissf requested changes

2023-11-09 07:17 UTC, rubenporras commented on com.avaloq.tools.ddk.test.ui/src/com/avaloq/tools/ddk/test/ui/junit/runners/TestRunRecording.java
> +        trace.append("TEST FAILED: ").append(exception.getClass().getSimpleName()).append(colonWithSpace).append(exception.getMessage()).append(newLine);
yes, of course. Done.

2023-11-09 07:24 UTC, joaodinissf approved these changes

2023-11-09 07:40 UTC, merged